### ISSUE TITLE
Build error when compiling on docker (linux)

### ISSUE THREAD

**Issue by obsean** [tocsoft/GraphQLCodeGen#24]
When building a docker linux container the build step will fail with the error error MSB4181: The "GenerateGraphQLClient" task returned false but did not log an error, even though it will build correctly on windows.

A simple sample can be found at https://github.com/obsean/GraphQlDocker. 

`dotnet build .\GraphQlDocker\GraphQlDocker.csproj` will succeed

 `docker-compose build` will fail with the above message

**Comment by tocsoft** [comment]
Thanks for find this, and for the reproduction... I've just pushing out a v0.2.0-beta.7 which should resolve your problem.

**Comment by obsean** [comment]
`/root/.nuget/packages/tocsoft.graphqlcodegen.msbuild/0.2.0-beta.7/build/Tocsoft.GraphQLCodeGen.MsBuild.targets(23,5): error MSB4181: The "GenerateGraphQLClient" task returned false but did not log an error. [/src/GraphQlDocker/GraphQlDocker.csproj]`

Still not working I'm afraid

**Comment by tocsoft** [comment]
ok figured out why it was working for me... its working if you target .net core 3.1 ... i'll continue looking into getting it working on .net5.0

**Comment by tocsoft** [comment]
`0.2.0-beta.8` should now fix it for net5.0 ... I hope 😁

**Comment by obsean** [comment]
That worked perfectly thanks!
